//! The `howl-note-v1` discovery record: 246 payload bytes inside a 256-byte PIR cell.
//!
//! The layout is frozen wire: an implementation on the other side of the network decodes by
//! these offsets. It is transcribed from Howl's committed codec, and the vectors in `tests/`
//! are generated by that codec's own arithmetic.
//!
//! Two of the seven transmitted ciphertext words are dropped by the server because the client
//! can recompute both - word 0 is a compile-time constant and word 5 is the owner, which a
//! recipient must be able to derive or it could not spend the note. This crate carries the
//! five survivors verbatim; reconstruction is the client's and is not implemented here.
//!
//! **The trailing ten bytes are part of the contract and must be zero.** Howl's decoder
//! refuses a non-zero tail, on the grounds that it means the sender used a layout this build
//! cannot read. See [`RecordError::NonZeroPadding`], and the note on `occurrence_count` there.

#![deny(missing_docs)]

use ark_bn254::Fr;
use ark_ff::{BigInteger, PrimeField};

/// Payload bytes actually used by the record.
pub const RECORD_BYTES: usize = 246;

/// Full PIR cell width. The gap to [`RECORD_BYTES`] is zero padding, not payload.
pub const CELL_BYTES: usize = 256;

/// Bytes of the note commitment carried for local false-hit rejection.
pub const COMMITMENT_PREFIX_BYTES: usize = 16;

/// Indices, in the original seven-word ciphertext, of the words the server keeps.
pub const CIPHERTEXT_KEPT_INDICES: [usize; 5] = [1, 2, 3, 4, 6];

/// Layout version this build encodes and is willing to decode.
pub const LAYOUT_VERSION: u8 = 1;

/// A self note, minted by the wallet to itself.
pub const RECORD_KIND_SELF: u8 = 0;
/// An incoming note, addressed by an ephemeral key.
pub const RECORD_KIND_INCOMING: u8 = 1;

const OFF_LAYOUT: usize = 0;
const OFF_KIND: usize = 1;
const OFF_LEAF_INDEX: usize = 2;
const OFF_COMMITMENT_PREFIX: usize = 6;
const OFF_EPH_X: usize = 22;
const OFF_CEK_WRAP: usize = 54;
const OFF_CIPHERTEXT: usize = 86;
const FIELD_BYTES: usize = 32;

/// One decoded discovery row.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HowlNoteRecord {
    /// Always [`LAYOUT_VERSION`] for a record this build produced.
    pub layout_version: u8,
    /// [`RECORD_KIND_SELF`] or [`RECORD_KIND_INCOMING`].
    pub record_kind: u8,
    /// Position in the commitment tree. Needed for the nullifier and travels in the row
    /// because a probe scheme gives the client no tag-to-index map.
    pub leaf_index: u32,
    /// `commitment[0..16]`. A probe returns a row on a MISS too, so this is how a false hit is
    /// rejected locally.
    pub commitment_prefix: [u8; COMMITMENT_PREFIX_BYTES],
    /// Zero on a self row.
    pub ephemeral_pk_x: Fr,
    /// Zero on a self row.
    pub cek_wrap: Fr,
    /// The five surviving ciphertext words, in [`CIPHERTEXT_KEPT_INDICES`] order.
    pub ciphertext_kept: [Fr; 5],
}

/// Why a cell could not be decoded.
#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum RecordError {
    /// The buffer was not exactly one cell.
    #[error("cell is {len} bytes, expected {CELL_BYTES}")]
    WrongLength {
        /// Length supplied.
        len: usize,
    },
    /// Layout version is not the one this build reads.
    #[error("layout version {found} is not the supported {LAYOUT_VERSION}")]
    UnsupportedLayout {
        /// Version byte found.
        found: u8,
    },
    /// Record kind was neither self nor incoming.
    #[error("record kind {found} is neither self ({RECORD_KIND_SELF}) nor incoming ({RECORD_KIND_INCOMING})")]
    UnknownKind {
        /// Kind byte found.
        found: u8,
    },
    /// A byte in the trailing pad was not zero.
    ///
    /// Deliberately fatal rather than ignored. The pad is where a later layout would put new
    /// fields, so a non-zero tail means the sender is speaking a dialect this build cannot
    /// read, and decoding the prefix anyway would return a record that looks complete.
    #[error("cell padding is non-zero at byte {index}")]
    NonZeroPadding {
        /// First offending offset.
        index: usize,
    },
    /// A 32-byte field slot was at or above the BN254 scalar modulus.
    #[error("field at offset {offset} is not a canonical BN254 scalar")]
    NonCanonicalField {
        /// Offset of the offending slot.
        offset: usize,
    },
}

fn put_field(out: &mut [u8], offset: usize, value: Fr) -> Option<()> {
    let be = value.into_bigint().to_bytes_be();
    let slot = out.get_mut(offset..offset + FIELD_BYTES)?;
    slot.fill(0);
    let start = FIELD_BYTES.checked_sub(be.len())?;
    slot.get_mut(start..)?.copy_from_slice(&be);
    Some(())
}

fn read_field(cell: &[u8], offset: usize) -> Result<Fr, RecordError> {
    let slot = cell
        .get(offset..offset + FIELD_BYTES)
        .ok_or(RecordError::WrongLength { len: cell.len() })?;
    let fr = Fr::from_be_bytes_mod_order(slot);
    // Refused rather than reduced: reduction maps two distinct wire encodings to one record,
    // and the commitment check downstream would then pass for a cell nobody wrote.
    if fr.into_bigint().to_bytes_be() != slot {
        return Err(RecordError::NonCanonicalField { offset });
    }
    Ok(fr)
}

/// Encode a record into a full 256-byte cell.
///
/// # Examples
/// ```
/// use howl_record::{HowlNoteRecord, encode, CELL_BYTES, LAYOUT_VERSION, RECORD_KIND_SELF};
/// use ark_bn254::Fr;
/// let record = HowlNoteRecord {
///     layout_version: LAYOUT_VERSION,
///     record_kind: RECORD_KIND_SELF,
///     leaf_index: 7,
///     commitment_prefix: [0u8; 16],
///     ephemeral_pk_x: Fr::from(0u64),
///     cek_wrap: Fr::from(0u64),
///     ciphertext_kept: [Fr::from(0u64); 5],
/// };
/// assert_eq!(encode(&record).len(), CELL_BYTES);
/// ```
#[must_use]
pub fn encode(record: &HowlNoteRecord) -> [u8; CELL_BYTES] {
    let mut out = [0u8; CELL_BYTES];
    if let Some(slot) = out.get_mut(OFF_LAYOUT) {
        *slot = record.layout_version;
    }
    if let Some(slot) = out.get_mut(OFF_KIND) {
        *slot = record.record_kind;
    }
    if let Some(slot) = out.get_mut(OFF_LEAF_INDEX..OFF_LEAF_INDEX + 4) {
        slot.copy_from_slice(&record.leaf_index.to_be_bytes());
    }
    if let Some(slot) =
        out.get_mut(OFF_COMMITMENT_PREFIX..OFF_COMMITMENT_PREFIX + COMMITMENT_PREFIX_BYTES)
    {
        slot.copy_from_slice(&record.commitment_prefix);
    }
    let _ = put_field(&mut out, OFF_EPH_X, record.ephemeral_pk_x);
    let _ = put_field(&mut out, OFF_CEK_WRAP, record.cek_wrap);
    for (i, word) in record.ciphertext_kept.iter().enumerate() {
        let _ = put_field(&mut out, OFF_CIPHERTEXT + i * FIELD_BYTES, *word);
    }
    out
}

/// Decode a full 256-byte cell.
///
/// # Errors
/// See [`RecordError`]. Every check is fatal; there is no lenient mode, because a discovery
/// row that decodes partially is indistinguishable from a probe miss downstream.
///
/// # Examples
/// ```
/// use howl_record::{decode, CELL_BYTES, RecordError};
/// let err = decode(&[0u8; CELL_BYTES]).unwrap_err();
/// assert!(matches!(err, RecordError::UnsupportedLayout { found: 0 }));
/// ```
pub fn decode(cell: &[u8]) -> Result<HowlNoteRecord, RecordError> {
    if cell.len() != CELL_BYTES {
        return Err(RecordError::WrongLength { len: cell.len() });
    }
    let layout_version = cell.get(OFF_LAYOUT).copied().unwrap_or_default();
    if layout_version != LAYOUT_VERSION {
        return Err(RecordError::UnsupportedLayout {
            found: layout_version,
        });
    }
    let record_kind = cell.get(OFF_KIND).copied().unwrap_or_default();
    if record_kind != RECORD_KIND_SELF && record_kind != RECORD_KIND_INCOMING {
        return Err(RecordError::UnknownKind { found: record_kind });
    }
    for index in RECORD_BYTES..CELL_BYTES {
        if cell.get(index).copied().unwrap_or_default() != 0 {
            return Err(RecordError::NonZeroPadding { index });
        }
    }
    let mut leaf = [0u8; 4];
    leaf.copy_from_slice(
        cell.get(OFF_LEAF_INDEX..OFF_LEAF_INDEX + 4)
            .ok_or(RecordError::WrongLength { len: cell.len() })?,
    );
    let mut commitment_prefix = [0u8; COMMITMENT_PREFIX_BYTES];
    commitment_prefix.copy_from_slice(
        cell.get(OFF_COMMITMENT_PREFIX..OFF_COMMITMENT_PREFIX + COMMITMENT_PREFIX_BYTES)
            .ok_or(RecordError::WrongLength { len: cell.len() })?,
    );
    let mut ciphertext_kept = [Fr::from(0u64); 5];
    for (i, slot) in ciphertext_kept.iter_mut().enumerate() {
        *slot = read_field(cell, OFF_CIPHERTEXT + i * FIELD_BYTES)?;
    }
    Ok(HowlNoteRecord {
        layout_version,
        record_kind,
        leaf_index: u32::from_be_bytes(leaf),
        commitment_prefix,
        ephemeral_pk_x: read_field(cell, OFF_EPH_X)?,
        cek_wrap: read_field(cell, OFF_CEK_WRAP)?,
        ciphertext_kept,
    })
}

/// Whether a decoded row plausibly belongs to a commitment the client recomputed.
///
/// A probe returns a row on a miss, so this is the local false-hit rejection. It is a
/// 16-byte prefix comparison and therefore NOT proof of ownership; the leaf check downstream
/// is what settles that.
#[must_use]
pub fn commitment_prefix_matches(record: &HowlNoteRecord, commitment: Fr) -> bool {
    let be = commitment.into_bigint().to_bytes_be();
    let mut full = [0u8; FIELD_BYTES];
    let start = FIELD_BYTES.saturating_sub(be.len());
    if let Some(slot) = full.get_mut(start..) {
        slot.copy_from_slice(&be);
    }
    full.get(..COMMITMENT_PREFIX_BYTES)
        .is_some_and(|expected| expected == record.commitment_prefix)
}
