#!/usr/bin/env bash
set -euo pipefail

poseidon_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
generator_dir="$poseidon_root/tests/generators"
vector_dir="$poseidon_root/tests/vectors"
scratch=$(mktemp -d "${TMPDIR:-/tmp}/howl-poseidon2-provenance.XXXXXX")
trap 'rm -rf -- "$scratch"' EXIT

expected_inventory=$'SHA256SUMS\naztec-foundation.mjs\ngen-kats.mjs\ngen-perm-kats.mjs\nreference-oracle.mjs\nreference.py\nyul-constants.json'
actual_inventory=$(find "$generator_dir" -mindepth 1 -maxdepth 1 -printf '%f\n' | LC_ALL=C sort)
if [[ "$actual_inventory" != "$expected_inventory" ]]; then
  printf 'Poseidon2 provenance packet inventory mismatch\n' >&2
  diff -u <(printf '%s\n' "$expected_inventory") <(printf '%s\n' "$actual_inventory") >&2 || true
  exit 1
fi

if /usr/bin/grep -Eq '/(home|Users)/' "$generator_dir"/*.mjs; then
  printf 'Poseidon2 generator contains a non-portable absolute home path\n' >&2
  exit 1
fi

mapfile -t manifest_paths < <(awk '{ print $2 }' "$generator_dir/SHA256SUMS")
expected_paths=(
  aztec-foundation.mjs
  gen-kats.mjs
  gen-perm-kats.mjs
  reference-oracle.mjs
  reference.py
  yul-constants.json
  ../vectors/sponge.json
  ../vectors/permutation.json
)
if [[ "${manifest_paths[*]}" != "${expected_paths[*]}" ]]; then
  printf 'Poseidon2 SHA256SUMS path set or order mismatch\n' >&2
  exit 1
fi

declare -A approved_hashes=(
  [aztec-foundation.mjs]=21925a963fff52da153ad73da1274bfd583449236bd6f773ec4214b29856f165
  [gen-kats.mjs]=cf1ab25589fc05e226a192a52c4c96a1bc70eadac80132c69164337a06def4ec
  [gen-perm-kats.mjs]=6347e62105ae5e2216f0135f8018838ee5e4929866bf6edc7318155ca6288ebe
  [reference-oracle.mjs]=2825a7f6fd7c6f746c99970973152bf70f2cd03ec66f9a2443d9f71eab3bcd55
  [reference.py]=7052fd84cc799cda804efb9579cab121755d9c067e447ee42d8b69c695c45c8f
  [yul-constants.json]=b6758fc0c4bec472b0f81d9452a5e6da2d2692f16dddbddb5c10b74f526cf0b7
)
for asset in "${!approved_hashes[@]}"; do
  recorded=$(awk -v asset="$asset" '$2 == asset { print $1 }' "$generator_dir/SHA256SUMS")
  if [[ "$recorded" != "${approved_hashes[$asset]}" ]]; then
    printf 'approved provenance hash mismatch: %s\n' "$asset" >&2
    exit 1
  fi
done

(
  cd "$generator_dir"
  sha256sum -c SHA256SUMS
)

cp "$generator_dir/reference-oracle.mjs" "$generator_dir/yul-constants.json" "$scratch/"
sed \
  -e '3c\import { poseidon2Hash, Fr } from "./reference-oracle.mjs";' \
  -e '4d' \
  "$generator_dir/gen-kats.mjs" > "$scratch/gen-kats.mjs"
sed \
  -e '3c\import { poseidon2Permutation, Fr } from "./reference-oracle.mjs";' \
  -e '4d' \
  "$generator_dir/gen-perm-kats.mjs" > "$scratch/gen-perm-kats.mjs"

node "$scratch/gen-kats.mjs" > "$scratch/sponge.json"
node "$scratch/gen-perm-kats.mjs" > "$scratch/permutation.json"

if ! cmp -s "$scratch/sponge.json" "$vector_dir/sponge.json"; then
  printf 'regenerated sponge vectors differ from committed corpus\n' >&2
  exit 1
fi
if ! cmp -s "$scratch/permutation.json" "$vector_dir/permutation.json"; then
  printf 'regenerated permutation vectors differ from committed corpus\n' >&2
  exit 1
fi

node - "$scratch/sponge.json" "$scratch/permutation.json" <<'NODE'
const fs = require("node:fs");
const expected = [[process.argv[2], 75, "sponge"], [process.argv[3], 53, "permutation"]];
for (const [path, count, name] of expected) {
  const corpus = JSON.parse(fs.readFileSync(path, "utf8"));
  if (!Array.isArray(corpus.vectors) || corpus.vectors.length !== count) {
    throw new Error(`${name} vector count ${corpus.vectors?.length} != ${count}`);
  }
}
NODE

printf 'Poseidon2 provenance: 6 packet assets and 2 corpora hashed; 75 sponge and 53 permutation vectors regenerated byte-identically\n'
