#!/usr/bin/env bash
set -euo pipefail

poseidon_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
selftest_root=$(mktemp -d "${TMPDIR:-/tmp}/howl-poseidon2-provenance-selftest.XXXXXX")
trap 'rm -rf -- "$selftest_root"' EXIT

new_case() {
  local name=$1
  local case_root="$selftest_root/$name"
  cp -R "$poseidon_root" "$case_root"
  printf '%s\n' "$case_root"
}

expect_red() {
  local name=$1
  local expected=$2
  local case_root=$3
  local output="$selftest_root/$name.out"
  if "$case_root/check-provenance.sh" >"$output" 2>&1; then
    printf 'selftest %s unexpectedly passed\n' "$name" >&2
    exit 1
  fi
  if ! grep -Fq -- "$expected" "$output"; then
    printf 'selftest %s failed without expected diagnostic: %s\n' "$name" "$expected" >&2
    sed -n '1,80p' "$output" >&2
    exit 1
  fi
  printf 'RED %s\n' "$name"
}

control=$(new_case control)
"$control/check-provenance.sh" >"$selftest_root/control.out"
grep -Fq '75 sponge and 53 permutation vectors regenerated byte-identically' "$selftest_root/control.out"
printf 'GREEN unmodified control\n'

missing=$(new_case missing)
rm "$missing/tests/generators/SPEC.md"
expect_red missing 'packet inventory mismatch' "$missing"

unlisted=$(new_case unlisted)
printf 'unexpected\n' > "$unlisted/tests/generators/unlisted.txt"
expect_red unlisted 'packet inventory mismatch' "$unlisted"

modified=$(new_case modified)
printf '\n' >> "$modified/tests/generators/reference.py"
expect_red modified 'FAILED' "$modified"

seed=$(new_case generator_seed)
sed -i 's/88172645463325252n/88172645463325253n/' "$seed/tests/generators/gen-kats.mjs"
seed_hash=$(sha256sum "$seed/tests/generators/gen-kats.mjs" | awk '{ print $1 }')
sed -i -E "s/^[0-9a-f]{64}  gen-kats.mjs/$seed_hash  gen-kats.mjs/" "$seed/tests/generators/SHA256SUMS"
sed -i "s/2991b7bff6667b449c496dad17f5a22b6af34091d42d73d9d43fa41fcab5ad08/$seed_hash/" \
  "$seed/check-provenance.sh"
expect_red generator_seed 'regenerated sponge vectors differ from committed corpus' "$seed"

drift=$(new_case vector_drift)
node - "$drift/tests/vectors/sponge.json" <<'NODE'
const fs = require("node:fs");
const path = process.argv[2];
const corpus = JSON.parse(fs.readFileSync(path, "utf8"));
const output = corpus.vectors[0].output;
corpus.vectors[0].output = `${output.slice(0, -1)}${output.endsWith("0") ? "1" : "0"}`;
fs.writeFileSync(path, `${JSON.stringify(corpus, null, 2)}\n`);
NODE
drift_hash=$(sha256sum "$drift/tests/vectors/sponge.json" | awk '{ print $1 }')
sed -i -E "s|^[0-9a-f]{64}  ../vectors/sponge.json|$drift_hash  ../vectors/sponge.json|" \
  "$drift/tests/generators/SHA256SUMS"
expect_red vector_drift 'regenerated sponge vectors differ from committed corpus' "$drift"

printf 'Poseidon2 provenance selftest: 1 GREEN control; 5 RED corruptions\n'
